#!/bin/bash
# zip up *.js *.json *.ico LICENSE README.md into ffally-githash.zip

name="ffally-$(git rev-parse --short HEAD).zip"
[ -f "$name" ] && rm "$name"
zip $name *.js *.json *.ico LICENSE README.md
echo "Created $name"
